name: Docker Cloud Build (Multi-Arch)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set up Docker Buildx (use cloud builder)
      uses: docker/setup-buildx-action@v3
      with:
        endpoint: cloud-demonstrationorg-default

    - name: Show available builders (optional)
      run: docker buildx ls

    - name: Extract short SHA
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Build and push (multi-arch with unique tag)
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        builder: cloud-demonstrationorg-default
        platforms: linux/amd64,linux/arm64
        provenance: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/spring:latest
          ${{ secrets.DOCKER_USERNAME }}/spring:${{ steps.vars.outputs.sha_short }}
